### ISSUE TITLE
pip install ansible

### ISSUE THREAD

**Issue by camronlevanger** [camronlevanger/ansible#3]
Pip is the easiest way to get the latest Ansible versions, but it does require the user to have already installed Pip.

I may update this to just mention the pip install, but not go into the details of installing Pip if it isn't present.

| commit | file reference | pull request |  |
| --- | --- | --- | --- |
| 6751c85207a334ece9f40006b81b2c4b99ea5b21 | [README.md#L10-L16](https://github.com/camronlevanger/ansible/blob/6751c85207a334ece9f40006b81b2c4b99ea5b21/README.md#L10-L16) | #2 | [![#2](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/camronlevanger/ansible/pull/2) |

**Comment by cparkins** [comment]
I'm not familiar with pip, the instructions were based on how I installed it.  My experience was that the playbook didn't work with just an apt-get install ansible because the Ubuntu repositories were using an older version.  Now I've read the installation instructions for ansible and would suggest a link to there.
